version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      # install dependencies in both apps
      - run:
          name: Back-End Install
          command: |
            cd udagram-api
            npm run backend:install
            cd ..
      - run:
          name: Back-End Build
          command: |
            cd udagram-api
            npm run backend:build
            cd ..
      - run:
          name: Back-End Deploy
          command: |
            cd udagram-api
            npm run backend:deploy
            cd ..
      - run:
          name: Front-End Install
          command: |
            cd udagram-frontend
            npm run frontend:install
            cd ..
      - run:
          name: Front-End Build
          command: |
            cd udagram-frontend
            npm run frontend:build
            cd ..
      - run:
          name: Front-End Deploy
          command: |
            cd udagram-frontend
            npm run frontend:deploy
            cd ..